In [ ]:
## NumPy library 

In [3]:
import numpy as np

In [54]:
#create arrays
print("version:",np.__version__)
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.dtype)

version: 1.21.5
[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [115]:
#dimensions in arrays
arr0 = np.array(12) # 0-D array
arr1 = np.array([5,6,7,8]) # 1-D array
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # 2-D array(matrice)
print("2-D array\n",arr2)
# number of dimensions with ndim attribute
print("dimension of arr1:",arr1.ndim) 
print("dimension of arr2:",arr2.ndim)
print("size of array2:",arr2.size)

2-D array
 [[1 2 3 4]
 [5 6 7 8]]
dimension of arr1: 1
dimension of arr2: 2
size of array2: 8


In [119]:
#access array elements
arr = np.array([1,2,3,4])
print("first element in array:",arr[0])
print("last element int array:",arr[-1])
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # 2-D array
print(arr2)
print("The element in row 0 and column 1 is:",arr2[0,1])
print("Last element from 2nd dim is:",arr2[1,-1])

first element in array: 1
last element int array: 4
[[1 2 3 4]
 [5 6 7 8]]
The element in row 0 and column 1 is: 2
Last element from 2nd dim is: 8


In [122]:
#slicing arrays
#[start:end] also [start:end:step]
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:6])
print(arr[:4])
print(arr[2:])
print(arr[-6:-1]) #negative slicing
arr2 = np.array([4,5,6,7,8,9,10])
print(arr2[2:6:2]) #determine step of the slicing
arr3 = np.array([[3,4,6,7],[8,7,5,4]]) # 2-D array
print(arr3[0,1:3])
print(arr3[0:2,2])
print(arr3[:,3])
print(arr3[0:2,0:3])
print(arr[::-1])

[2 3 4 5 6]
[1 2 3 4]
[3 4 5 6 7 8]
[3 4 5 6 7]
[6 8]
[4 6]
[6 5]
[7 4]
[[3 4 6]
 [8 7 5]]
[1 2 3 4 5 6 7]


In [38]:
#data types
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.dtype)
arr2 = np.array(["emre","ali","mustafa"],dtype='S') # creating array with defined data type 
print(arr2.dtype)
#change the data type with astype() method
newarr = arr.astype('f')
print(newarr.dtype)
print(newarr)

#copy() and view()
oriarr = np.array([[1,2],[4,6],[2,4]])
arrc = oriarr.copy()
print(arrc)
arrc[1,0] = 10 # will not affect original array
print("original array.\n",oriarr)
arrv =oriarr.view()
arrv[1,0] = 10 # will affect  original array
print("original array.\n",oriarr)
print("check if array owns its data")
#base
print(arrc.base) # return none -> copy() method
print(arrv.base) # refers the original object -> view() method

int32
|S7
float32
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[1 2]
 [4 6]
 [2 4]]
original array.
 [[1 2]
 [4 6]
 [2 4]]
original array.
 [[ 1  2]
 [10  6]
 [ 2  4]]
check if array owns its data
None
[[ 1  2]
 [10  6]
 [ 2  4]]


In [98]:
# shape
# returns a tupple
arr = np.array([[4,5,6],[1,2,4]])
print("shape of array:",arr.shape) # return (2,3) ,array has 2 dimensions. First dimension has 2 elements and the second has 3.
#reshape
arr2 = np.array([1,2,3,4,5,6,7,8,9])
print(arr2.reshape(3,3))
#reshape(-1)
arr2 = np.array([[4,6,7],[12,76,2]])
print(arr2.ravel()) # =  reshape(-1) method which is converting array into a 1D array 

shape of array: (2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 4  6  7 12 76  2]


In [113]:
arr = np.zeros((2,4))
print(arr)
arr2 = np.ones((3,5))
print("\n",arr2)
arr3 = np.empty((4,3))
print("\n",arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[4.45057637e-308 1.78021527e-306 8.45549797e-307]
 [1.37962049e-306 1.11260619e-306 1.78010255e-306]
 [1.42409073e-306 4.45058910e-308 8.45596650e-307]
 [9.34602321e-307 4.94065646e-322 4.93432906e+257]]


In [125]:
arr = np.arange(9,21,3)
print(arr)
arr2 = np.linspace(0,10,5)
print(arr2)


[ 9 12 15 18]
[ 0.   2.5  5.   7.5 10. ]


In [85]:
arr = np.array([1,7,3])
arr2 = np.array([4,5,6])
print(arr+arr2)
print(arr*arr2)
print(arr-arr2)
print(arr/arr2)
print(arr%arr2)

[ 5 12  9]
[ 4 35 18]
[-3  2 -3]
[0.25 1.4  0.5 ]
[1 2 3]


In [86]:
liste = [1,2,3,4]
arr = np.array([1,2,3,4])
print(liste)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [90]:
a = np.array([1,2,3])
b = a
c = b
c[1] = 10
print(a,b,c)

[ 1 10  3] [ 1 10  3] [ 1 10  3]


In [99]:
#transpose
arr = np.array([[1,2,4],[5,6,7]])
print(arr.T)

[[1 5]
 [2 6]
 [4 7]]


In [123]:
#iterating arrays
arr = np.array([1,2,3,4,5])
for item in arr:
    print(item)
arr2 = np.array([[1,2,3],[4,5,6]])
for item in arr2:
    for item2 in item:
        print(item2)
#nditer()  function
print("using nditer function")
for item in np.nditer(arr2):
    print(item)
 #ndenumerate() function
for id,item in np.ndenumerate(arr2):
    print(id,item)

1
2
3
4
5
1
2
3
4
5
6
using nditer function
1
2
3
4
5
6
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
